### ISSUE TITLE
Cannot bind <FocusOut> event to entry widget

### ISSUE THREAD

**Issue by jamesgrahamstneots** [jarvisteach/appJar#100]
app.setEntryFunction("slave3entry", printing, "<FocusOut>") does not function. Would be really useful if this was working

**Comment by jarvisteach** [comment]
Firstly, appJar supports the following 3 function options for widgets:
* setXXXFunction - called when a widget *changes*
* setXXXOverFunction - called when the mouse enters and/or leaves a widget
* setXXXDragFunction - called when the mouse is clicked/released in a widget

I've just had a quick look, and over/drag currently only work on Labels. Don't remember if there's any reason why I left it at only those widget types - probably just due to a lack of testing.

I don't see any reason why they won't work on other widgets, so I'll raise a change request to extend that functionality to all widgets.

As to the ```<FocusOut>``` event, there's no way to bind to that directly through appJar (even though it's already bound internally for updating default values).

However, you can achieve it using standard tkinter code:
```
app.getEntryWidget("slave3entry").bind("<FocusOut>", printing, add="+")
```

**Comment by jamesgrahamstneots** [comment]
That's great, I appreciate your help. Thanks very much

**Comment by jarvisteach** [comment]
Look into providing functions for other bindings.

**Comment by pinchies** [comment]
I had the same exact issue last week and was wondering why the setXXXfunction wasnt working for entries. The documentation wasn't clear enough for me that this was limited to some widget types. It would be great if both setXXXfunction and some blur/lose focus function was available for entries. As at the moment there is no way to know when the entry value has been changed, and no way to know when the entry has lost focus, and both provide great value for creating dynamic interfaces. 

Appjar was really easy otherwise, so thanks for all the hard work. I used Appinstaller to bake my app into an exe which went quite smoothly.

**Comment by jarvisteach** [comment]
You're right, the documentation is unclear...

Originally, setXXXFunction was to allow the <enter> key to be pressed in an entry to 'submit' the entry.

It's grown since then to cover changes to a scale/option/list box, then to include clicking on a label or image. Finally, I made it generic, so that it links to any widget.

I'll update the documentation to make it more clear, and add another change request to get more options on the Entry...

**Comment by jarvisteach** [comment]
Issue resolved.
