### ISSUE TITLE
ColourMap in documentation has invalid colours

### ISSUE THREAD

**Issue by captainsmu** [jarvisteach/appJar#105]
The colour 'Crimson' doesn't seem to work.  I've tried about 15 other colours from the colour map and they seem to work OK.

**Comment by jarvisteach** [comment]
This is nothing to do with appJar...

The colourmap, http://appjar.info/pythonBasics/#colour-map, is just an image I included in the docs for the kids at school, so they had ideas of what was available.

Turns out you're right, the image is wrong - crimson is not supported... it's possible it used to be in an older version of tkinter (as that's where I assume the colour names are stored) but no longer is.

I'll look for another colormap image and update the docs

**Comment by jarvisteach** [comment]
Going over this again, crimson is accepted on both OSX & Linux in Python 2 & 3.

It looks like the colour names may just vary from version to version & platform to platform.

I'm going to close this as a won't fix.
