### ISSUE TITLE
Issue with sub windows - modal not working

### ISSUE THREAD

**Issue by jacobthetechy** [jarvisteach/appJar#108]
```
def openLogin():
    app.showSubWindow('L')


app = gui('SLA Sendback Entry')

# Login #
app.startSubWindow("L", modal=True)
app.addLabelEntry('Username')
app.setFocus('Username')
app.addLabelSecretEntry('Password')
app.addButton('Login', login)
app.stopSubWindow()

app.addLabelEntry('Entry')
app.setFocus('Entry')

openLogin()
```
 Above code will not open any window. When you remove `modal=true` it works.

python 2.7.12
Windows 7

**Comment by jarvisteach** [comment]
There's an issue in the above code, in that it doesn't call ```app.go()```.
That results in lots of setup not being completed, including the eventLoop not being started.
So, that may be causing some issues...

However, I see two things to investigate here:

1) Is the modal flag working properly - I know there have been some issues with it in the past, especially cross-platform.

2) How best to support multiple windows... appJar is designed to have a main window (the app), but grew to support subWindows - allowing popUps to be launched. I'm seeing more & more use cases like this, where people want the subWindows to launch first, and only to show the main window, once the user has logged in (for example).

I'll keep this issue open as an investigation into modal, and will raise a new issue to consider how to best implement a sequence of windows being used, and how to specify showing a subWindow first, rather than the main app...

**Comment by jacobthetechy** [comment]
The work around was to take the modal out and to place a transparency on the main window until the user logged in. When that was successful i then hid the subwindow and changed the transparency back to the main window.

Ill post the code tomorrow morning when I'm back at work.

**Comment by jarvisteach** [comment]
Next_release will have ```.hide()``` & ```.show()``` for the main window, along with a parameter to the ```.go()``` function to allow starting with a *SubWindow*. See issue #112

**Comment by jarvisteach** [comment]
@jacobthetechy I've looked into this some more.

Setting the popup as `modal=True`  and then calling `openLogin()` pauses the code at that point. Execution never gets to the call to `app.go()`, which means none of the windows ever get drawn on the screen.

When `modal=False` the call to `openLogin()` doesn't block, allowing `app.go()` to be reached, and therefore the windows to be drawn.

This explains the issues you had with your original code.

The changes mentioned above also break when `modal=True`.  Calling `app.hide()` when a modal dialog is showing will hide both the min window an the modal window - I guess the two are quite closely linked.

The changes above also don't cater for having the main window launch, with a dialog drawn above it - which may have been your original use case?

**Comment by jarvisteach** [comment]
Modal dialogs have a few few function calls available:
1) `<modal_win>.focus_set()` - give the dialog focus
2) `<modal_win>.transient(<parent_win>) - links it to the parent, rather than being standalone
3) `<modal_win>.grab_set()` creates modality - it stops events firing on any other windows
4) `<parent_win>.wait(<modal_win>)` tells the parent to effectively not close until modal has been closed

If the user is declaring a modal window, they definitely want 1 & 3.

2 & 4 are not necessarily characteristics of modal windows, they should be configurable separately:
* `.setBlocking()` to tell the modal not to return
* `.setTransient()` to tell the modal to not act like a normal window

**Comment by jarvisteach** [comment]
`.startSubWindow()` now has two additional parameters: `transient` & `blocking` these are configured when creating the SubWindow, and will be applied accordingly.

Final thing to look into is grouping - it's being configured in the SubWindow, and there is a parameter for it, but it's not documented.

loo can update testing now, to include some modal windows...

**Comment by jarvisteach** [comment]
Also, app.go() with a blocking dialog should fail - with an error message...

**Comment by jarvisteach** [comment]
Grouping raised as a new issue (#144) 

Closing issue, as all investigation and changes have been made here...
