### ISSUE TITLE
'SimpleGrid' object has no attribute 'ent_but'

### ISSUE THREAD

**Issue by EmeraldNight** [jarvisteach/appJar#158]
I've been trying to use AppJar to set up some simple tools to use in managing the World of Tanks clan i'm in. What i currently have consists of a grid that's supposed to layout the players of the selected clan. Everything in the program works fine up until i try to add a grid row:

`addGridRow("datagrid", [PlayerRank, PlayerAccountName, PlayerID, LastBattleDate, DaysSinceLB, Battles])`

When this hits I get "'SimpleGrid' object has no attribute 'ent_but'" thrown back at me.

**Comment by jarvisteach** [comment]
Yes, this is another bug with the grid widget!

When adding a new row, it currently assumes you have a row of entry boxes (with a button). It first tries to remove the entry boxes, then add the row, then re-show the entry boxes.

I guess you don't have any entry boxes!

A couple of other bugs have already been reported on this widget - it is due for a bunch of fixes in the next couple of weeks, I'll add this to the list!

**Comment by EmeraldNight** [comment]
Cool, throw adding entry boxes should work as a temporary workaround?

**Comment by jarvisteach** [comment]
If you set `action` to point at a function, and set `addRow` to be True you'll be able to add rows, but you'll get all the extras that you might not want...

**Comment by SecretShop** [comment]
I am newer to Python and i also ran across this problem when trying to populate a table with information. 
I tried the following work around as stated:
showData.addGrid("g1",[["#", "Game ID", "Champ"]], nothin(), True)

nothin() is just a useless function, and i assume i set AddRow to True. Am i missing something? Thanks you!

**Comment by jarvisteach** [comment]
Hi @SecretShop, could you give a bit more information, including the error message. Thanks.

**Comment by SecretShop** [comment]
`import sqlite3
from appJar import gui

def nothin():
    print("ndkjskj")

conn = sqlite3.connect('Ranked_Data.db')
c = conn.cursor()
showData = gui("Ranked Statistics")
c.execute('SELECT GAMEID, CHAMP FROM RANKED')
stuff = c.fetchall()
showData.addGrid("g1",[["#", "Game ID", "Champ"]],nothin(),True)
for k in range(1,len(stuff)):
    showData.addGridRow("g1",[k, stuff[k][0], stuff[k][1]])
print("Total games: {}".format(len(stuff)))
showData.go()`

That is the code that i used if you would like to try yourself but it throws the following errors:

Traceback (most recent call last):
  File "C:\Users\Shot2400\Desktop\Tut\lists.py", line 14, in <module>
    showData.addGridRow("g1",[k, stuff[k][0], stuff[k][1]])
  File "C:\Users\Shot2400\AppData\Local\Programs\Python\Python36\lib\site-packages\appJar\appjar.py", line 3049, in addGridRow
    self.__verifyItem(self.n_grids, title).addRow(data)
  File "C:\Users\Shot2400\AppData\Local\Programs\Python\Python36\lib\site-packages\appJar\appjar.py", line 9312, in addRow
    self.__removeEntryBoxes()
  File "C:\Users\Shot2400\AppData\Local\Programs\Python\Python36\lib\site-packages\appJar\appjar.py", line 9379, in __removeEntryBoxes
    self.ent_but.lab.grid_forget()
AttributeError: 'SimpleGrid' object has no attribute 'ent_but'

I understand the issue is being looked into i just would like to use a work around for now. Once again thank you very much!
