### ISSUE TITLE
.addButtons and referencing functions

### ISSUE THREAD

**Issue by steveo-ct** [jarvisteach/appJar#201]
I'm trying to pass custom variables to the functions listed in the buttons path. They aren't working correctly and are generating no errors:

def btnSave(name):
    print('Save')
    
def btnReset(name, lblnames):
    print('Reset')
    
def btnCancel(name):
    app.stop()

app.addButtons(["Save", "Reset", "Cancel"], [btnSave, btnReset(name,lblnames), btnCancel], colspan=2)

lblnames is not being passed to the function, nor is the print action occurring. 
item to note: on application startup, the print('Reset') action is executed. "Reset" can be seen on the command line.

how can I pass a string to the button function? the string contains a list of the app fields names and will reset the fields. there's 20+ fields - text and drop downs.

**Comment by steveo-ct** [comment]
--- update ----
I found a small work around.
I'm able to clear half the form with app.clearAllEntries() and app.clearTextArea() however, the option boxes still remain set. I'm looking for a way to programmatically access the  fields to reset them without knowing their names; similar to the clearallentries function.

likewise (and probably a separate request) i'm looking for a way to programmatically get all the selected values from the option boxes without knowing their names. similar to the getallentries().

**Comment by jarvisteach** [comment]
A few different things here:
* First, you can't put brackets & parameters in the function list, as that causes the function to be called immediately. So instead of `app.addButtons(["Save", "Reset", "Cancel"], [btnSave, btnReset(name,lblnames), btnCancel])` make `lblnames` a global variable, and access it within the function.
* I'll raise separate feature requests for the option boxes - with the same naming convention as entries

For now, the optionBoxes are all stored in a dictionary: `app.n_options` and the associated variables are stored in a dictionary called: `app.n_optionVars`. So you can loop through them, and get their value and reset them:

```
for name in app.n_options:
    val = app.getOptionBox(name)
    app.setOptionBox(name, 0)
```

**Comment by steveo-ct** [comment]
That makes sense. Thanks for the response and noting the additional features.

regarding the loop, I attempted to set the option box value to 0 but receive a warning message: Warning - Invalid selection index: 0 is a disabled index.

that's printed to the console automatically. Is there a way to override it?

**Comment by jarvisteach** [comment]
Away from computer, so can't test now, but you can bypass the set functions:
```
for name, var in app.n_optionVars.items():
    val = app.getOptionBox(name)
    var.set(xxx)
```

**Comment by steveo-ct** [comment]
Thanks. I haven't tried the override code yet.
I changed the logic to remove the dropdown boxes and replaced them with autotext lists.
It made grabbing all the fields as well as resetting at once easier.

**Comment by jarvisteach** [comment]
Great - I will close this issue then, and get to work on the change request in #202
