### ISSUE TITLE
LabelFrame docs unclear - re. stickiness

### ISSUE THREAD

**Issue by steveo-ct** [jarvisteach/appJar#203]
I added a text area to a label frame and set the colspan of the text area = 2. The text area does not span across the columns.

Below is the test code i tried. When adding the text area 'notes' to the frame, it doesn't span 2 columns. Just adding the text area 'notes2' outside the labelframe adjusts the textarea across 2 columns.

here's the code:
from appJar import gui

app = gui("Dyanmic Test")

labelEntryNames = ['name', 'location', 'type']
labelOptionValues = ['select one', 'laptop', 'desktop', 'HDD Only']

#label frame to contain fields
app.startLabelFrame('Main', colspan=2)

for en in labelEntryNames:
    app.addLabelEntry(en, colspan=2)

app.addLabelOptionBox('Source', labelOptionValues, colspan=2)
app.addDatePicker('dp', colspan=2)
app.setDatePicker('dp')

app.addTextArea('notes', colspan=2)
app.stopLabelFrame()

#to test the span across the gui
app.addTextArea('notes2', colspan=2)
                
app.go()

**Comment by steveo-ct** [comment]
----Update----
After adding the textArea widget into the label frame, the stickiness of the text area widget has to be set to get it to span across the columns.

`#label frame to contain fields
app.startLabelFrame('Main')

for en in labelEntryNames:
    app.addLabelEntry(en)

app.addLabelOptionBox('Source', labelOptionValues)
app.addDatePicker('dp')
app.setDatePicker('dp')

app.setSticky('nesw')
app.addTextArea('notes')
app.stopLabelFrame()`

**Comment by jarvisteach** [comment]
In all these cases, colspan doesn't affect anything - it's only useful, if you've added widgets into multiple columns.

As you've worked out, how big the widget gets is down to its container's stickiness.

An appJar GUI will stick widgets to both sides E & W, but a LabelFrame only sticks widgets to the W edge. Setting sticky to EW is necessary in a LabelFrame, to get the widgets to fill expand across its width.

This is by design, although it's not specifically mentioned in the docs - I'll update the docs to make it clear that a LabelFrame works slightly differently to the appJar container - and give more examples.
