### ISSUE TITLE
ProgressMeter/SumOfEntries

### ISSUE THREAD

**Issue by coleyoungmusic** [jarvisteach/appJar#227]
I'm certain that I am doing something wrong in the code but I have not figured out how to correct it.  The two main issues that I am having deal with the progress meter and the entries.  For the entries it will only provide the sum of the bills when all entries are filled as opposed to it allowing me to be able to add say just two entries.  For the progress meter I can add values for the meter to go up but it starts to get glitchy after 14%.  You can clearly go up to 100% but it will go back and forth between the greater and lesser values.  In addition to this I'm not sure how to subtract values from the percentage completed once the user unselects a checkbox in the event they may  need to go back down to 0%.  
[BillManager.txt](https://github.com/jarvisteach/appJar/files/1250599/BillManager.txt)

**Comment by jarvisteach** [comment]
2 things here:

* If an Entry is empty, it returns an empty String - when you try to cast that as a float it will fail.
So, either use `app.addNumericEntry()` to ensure they only return numbers.
Or, check they are numbers before casting them as floats.

* The meter appears glitchy, because you are setting it to lots of different values very quickly, you need to move the calculation/setMeter outside of the loop:

```
for bill in billList:
    if bill is True:
        bill_value.append(14.2857142857)
addValues = sum(bill_value)
app.setMeter("Progress", addValues)
```
