### ISSUE TITLE
project name

### ISSUE THREAD

**Issue by keithterrill** [jarvisteach/appJar#239]
Googling appjar brings up such things appjar solutions web development, emenaceb apache, appjar on anaconda, and java.

Is it possible that this project should be renamed to something a little more unique? Perhaps something like: pythonJar or pythonAppJar?

Just wondering...

**Comment by jarvisteach** [comment]
Interesting - when I google appJar the whole first page is links to appJar related sites - appjar.info, wikipedia, github, youtube, pypi & stack overflow.

Bing & DuckDuckGo also put relevant links at the top, although there is some other stuff.

Are my search results skewed because Google knows what I search for? Do you not get relevant links at the top? That would be annoying, I was convinced googling worked :(

I'm aware that jar files are java archives, and that might be cause for confusion, but I'm not too worried about that...

**Comment by keithterrill** [comment]
After a few more searches, my Google is now floating more of your appJar to the top of the list. Perhaps, google is more intelligent than at first thought.

On second thought, having a slight confusion may get some java users to look a little more at python and the appJar.

carry on...

**Comment by jarvisteach** [comment]
I was hoping I'd done enough SEO to allow people to find the site if they googled appjar

I'll put some more effort into getting python/tkinter/gui into the SEO...
