### ISSUE TITLE
Option to set default padding values?

### ISSUE THREAD

**Issue by mpmc** [jarvisteach/appJar#361]
There's no obvious way to set the default padding/inpadding for all widgets. Now that we have getters/setters would it be possible to have an option to set these? For example..

```python
app.padding = 5, 5
app.inpadding, 6, 6
```

**Comment by jarvisteach** [comment]
*defaults* are kind of already there (or at least supposed to be), and both of those properties exist: [GUI Properties](http://appjar.info/simpleAppJar/#gui-properties_1)

When you set any properties, they are stored against the current container, whenever anything is added to that container, the defaults should be used.

These don't propagate fully into subContainers, as subContainers have their own defaults, so that might be something to look into...

It's also (becoming) possible to pass them as parameters when starting a container, or when adding a widget - whatever is based here will update the current container's defaults.

A lot of this already exists in the current release, and will be *officially* rolled out in the 1.0 release.

**Comment by mpmc** [comment]
> These don't propagate fully into subContainers, as subContainers have their own defaults, so that might be something to look into...

I think this is what the problem is :+1: 

---

`removeAllWidgets` seems to reset padding to zero. I'm working around this by using my own method of the same name, calling the super & setting the padding again.

```python
    def removeAllWidgets(self, *args, **kwargs):
        """Set default padding after clearing."""
        super().removeAllWidgets(*args, **kwargs)
        self.padding = 3, 3
        self.inpadding = 3, 3
```

**Comment by jarvisteach** [comment]
Closing as #55 will deal with this.
