### ISSUE TITLE
TickBox option list does not work on Mac

### ISSUE THREAD

**Issue by frakman1** [jarvisteach/appJar#365]
On my MacOS 10.12.6 Sierra.
Python version 3.6.4
latest appJar as of today (appJar-0.90.0-py3.6)

The Tick Option Box does `NOT` show a tick when I select it from the pull down.
However, the getOptionBox dictionary clearly shows `Mice` as selected (True). See screenshot below:

![image](https://user-images.githubusercontent.com/5826484/35773796-63ba491c-092a-11e8-9242-982f75a4ba13.png)

Code:

``` python
from appJar import gui

def press(btn):
    print(app.getOptionBox("Animals"))

app=gui()
app.setFont(20)

app.addTickOptionBox("Animals", ["Dogs", "Cats", "Elephants", "Mice"],0,0)
app.addButton("Check Tick", press,0,1)

app.go()
```

**Comment by jarvisteach** [comment]
@frakman1 - I think this is an issue with tkinter, rather than appJar.

I'm pretty sure that Mac won't show the ticks in either option boxes or menus. The items are acting as if they are tick boxes, and know their state, they just don't graphically show it...

I know it works on other platforms, but I think Mac stops it from working. I'll do some digging/testing to confirm. But I am pretty sure it's a known *feature* of tkinter on Mac.

If it is, I'll update the docs, and add a warning message to the code. If there is a work around, I'll see if I can find it...

**Comment by frakman1** [comment]
@jarvisteach Thank you for the response. The strange thing is that the demo/documentation had a screenshot of it working on a Mac. Did it stop working at some point?

![image](https://user-images.githubusercontent.com/5826484/35838973-fc62fff0-0abb-11e8-8ebf-8314a490c21e.png)

**Comment by jarvisteach** [comment]
You're right, it definitely did once work....
But, back in issue #42 it started having issues, I think it was broken in a newer version pf TCL/TK, I will keep digging though,

**Comment by jarvisteach** [comment]
This is now logged as a limitation.
