### ISSUE TITLE
Hide horizontal scrollbar in ScrollPane?

### ISSUE THREAD

**Issue by The-Sleepy-Penguin** [jarvisteach/appJar#369]
Hi,
As said in the title, are there any options to hide the horizontal scrollbar in the ScrollPane? ie. The user can only scroll up/down.
Thanks!

**Comment by jarvisteach** [comment]
definitely possible...

They're meant to autohide, if not being used, but we could introduce flags to disable/enable them

**Comment by jarvisteach** [comment]
Hi @The-Sleepy-Penguin - Ive tested this and the scrollbars are auto-hiding, so they only show when required.

So, are you requesting a feature where the scrollbars can be disabled, so the GUI will grow to accommodate its contents, rather than show a scrollbar?

Instead of adding functions to hide/show scrollbars, we could have a flag to disable one of the scrollbars when the pane is created, with no ability to re-enable it later?

**Comment by The-Sleepy-Penguin** [comment]
Yes, I was asking for a feature that would make the GUI grow rather then show a scrollbar.
