### ISSUE TITLE
SpinBox Change Function not getting called.

### ISSUE THREAD

**Issue by frakman1** [jarvisteach/appJar#442]
![image](https://user-images.githubusercontent.com/5826484/38954099-c79dfb62-431e-11e8-8560-c057adbf6558.png)

When using `setSpinBoxChangeFunction`, I have noticed that the change function only gets called when I click the up/down arrows on a spin box. So far so good.

However, when I select the number in the spinbox and type over it with the keyboard and press enter, this is not registered as a change and is completely ignored by the code, despite updating in the GUI. This is odd since it appears to have changed visually, but no code feedback is registered.

Is there any way to fix this or is this considered 'works as designed' ?

Thank you

**Comment by jarvisteach** [comment]
This is interesting - I definitely think it's not "desired"...

The change function also gets called if the arrow keys are used to navigate up and down through the spin box. So it must be a 'feature' of the underlying tkinter implementation. I'll do some digging, the event may need to be registered against the associated variable, rather than the widget itself...

**Comment by jarvisteach** [comment]
This is now resolved in the next release

**Comment by frakman1** [comment]
Marvelous!  Thank you very much!
