### ISSUE TITLE
Updating listbox values with new .listbox() method does not seem to work

### ISSUE THREAD

**Issue by EddyBag42** [jarvisteach/appJar#446]
Simplifications of upcoming appJar v1.0 are already available in 0.92 so i began to test them. They are a considerable improvement of appJar in my opinion, and I'm very interested in using appJar v1.0 with my students. So first of all i want to thank you for your great job !
I wanted to tell you that I noticed that updating values of a list box in v1.0 style, with some instruction like `app.listbox('mylistbox', mylistofvalues)`, does not yet work as it should (it does nothing at all). For now it seems to me that you have to stick to the "old way", that is `app.updateListBox('mylistbox', mylistofvalues)`. 
Hope this helps though it's a really tiny bug (more an occasion to thank you than anything else ;-)).

**Comment by jarvisteach** [comment]
Thanks for the comments!

At the moment, I think all of the list style widgets (option, list & spin) are set to *select* the parameter received when an already existing widget is referenced.

I remember trying to decide what was best here - what is the most common use case. I came to the conclusion that it would be *selecting* an item, rather than updating the whole list.

And, as the listbox supports multi-select, it will accept a list of values to select.

So, first there should be an error I assume none of the items in your new list were in your old list - appJar should warn you about this.

And, second, there should be some way to specify to update/append/select items in the list...

**Comment by EddyBag42** [comment]
Ok ! I saw in your code that the behavior was selecting but i didn't think enough about it to understand why ... Now i do ;-)

You're right, none of the items in the new list where in the old list, but as old list was an empty list this didn't throw any error ...

I really liked the design choice you made deciding `app.widget('label')` would be a getter and `app.widget('label',values)` would be a constructor/setter. In fact I liked it so much that i didn't understand until now that some widgets were not following this rule, like listboxes ... Another example with listboxes is that, to follow this rule, `app.listbox('mylistbox')` should not return selection as it does now (being equivalent to `app.getListBox('mylistbox')`) but the complete values list used to build the listbox (like `app.getAllListItems('mylistbox')`). 

You're right, there should be some way to specify to update/append/select items in the list, and it's clearly not such a simple question to decide which would be the most natural and simple way to get it done ...

**Comment by jarvisteach** [comment]
OK, I've introduced more error checking on the listbox, so hopefully you'll now get messages when strange things happen. I've also updated the docs to make it more clear.

I'm going to close this issue, and open a new one to discuss implementing the different changing features...
