### ISSUE TITLE
Setting column widths in Table.

### ISSUE THREAD

**Issue by dsanmartins** [jarvisteach/appJar#458]
Hi,

I tried to set the width of a column in a Table widget without successful. I used the function .setTableWidth() but nothing happens. The data come from a sqlite database and one field is text (a description with a lot of text). When the text is shown in the Table widget, the cell does not break it in multiple lines, just one line.

![table](https://user-images.githubusercontent.com/19354061/40311643-d81169f2-5ce6-11e8-8c21-b0da40e3983a.png)

Thanks!.

**Comment by jarvisteach** [comment]
Hi @dsanmartins - at the moment it's not possible to set individual column widths, they just scale to fit the data. This is obviously a problem, as in your case if the data is long the cell stretches.

We could look at using messages instead of labels, or making use of the `wrap length` property on labels - but I'll have to do a bit of investigation...

**Comment by dsanmartins** [comment]
Thank you for replying. Hope this can be fixed in the nearly future. By the way, it is a great project!

**Comment by jarvisteach** [comment]
It's now possible to set a wrap parameter on tables (number of pixels). It defaults to 250, setting it to 0 removes it.
