### ISSUE TITLE
Background image on SubWindow not working

### ISSUE THREAD

**Issue by Santi5010** [jarvisteach/appJar#556]
# Bug Report
Background image on SubWindow does not show

## Context
I've created a login Subwindow and wanted to set a background on it. 
I've also tried adding the image (not as background), like this:
photo = ImageTk.PhotoImage(Image.open('myimage.gif'))
app.addImageData("pic", photo, fmt="PhotoImage")
Which indeed works and adds the image after all of my widgets. Which would mean the background feature is faulty, not the adding images feature (unless I've done something wrong, of course).

## Expected Behaviour
Window pops up with the image shown as background. 

## Actual Behaviour
Window pops up as if I never wrote the .setBgImage line of code.

## Any error messages produced by appJar
None.

## Sample code, demonstrating the issue
This is the relevant piece of code:
app.openSubWindow('Iniciar sesión')
app.setBgImage('iniciosesion2.png')
app.stopSubWindow()

## What steps are needed to reproduce the bug
Exactly what I wrote. It was a 400x309 pixels image (I've also tried with a 2601*2011 pixels image, still no good result).

## Version Information
Python 3.6.0

**Comment by jarvisteach** [comment]
Hi @Santi5010 - yes, I think you're right, this isn't implemented yet in subWindows.

There are a couple of features like this which aren't fully implemented across both the main window and subWindows - things like toolbars/statusbars as well I think.

There's no reason why it cannot be added, it just hasn't been yet (mainly because bg images generally don't look so good...)

**Comment by jarvisteach** [comment]
Closing this as merged into #508
