### ISSUE TITLE
.setImage will not re-load images if file name doesn't change

### ISSUE THREAD

**Issue by aricooperdavis** [jarvisteach/appJar#87]
As title, the `.setImage` function will not update what is displayed by an Image widget if the image's filename/path does not change, even if the image itself does change.

This means that if another program updates the image then this change won't be reflected by the appJar app.

This is an issue with python applications that may use something like PIL to update images as they're in use by the appJar app.

Minimum working example attached.
[Image_Issue.zip](https://github.com/jarvisteach/appJar/files/717717/Image_Issue.zip)

**Comment by jarvisteach** [comment]
appJar caches images, based on filename.

There are therefore a couple of things that can be done here.  
1. Add a function to force an image reload: ```.reloadImage()``` This would be a trivial change, and would update the cache with the new image (even if it's the same).
2. Change image caching, so that instead of just image name, it also checks something else - a checksum ```hashlib.md5()``` or last modification date ```os.path.getmtime(path)```

I'll look into getting (1) added for the next patch release (due this weekend), and will add (2) to the backlog ...

**Comment by aricooperdavis** [comment]
Fantastic, (1) sounds absolutely perfect to me, thanks for your quick and efficient response!

**Comment by jarvisteach** [comment]
New version has been released (0.041) with reloadImage() function

**Comment by jarvisteach** [comment]
Hey @aricooperdavis , hope you don't mind, but I used your balloon image in a sample on the [images page](http://appjar.info/pythonImages/)

**Comment by aricooperdavis** [comment]
@jarvisteach I confess that I didn't create that image, I found it [here](https://stockphoto.zone/image/1678/balloon-png3387).
